using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SimpleTrap : MonoBehaviour {

    private Rigidbody[] rigid;
    [SerializeField]
    private GameObject go_Meat;

    [SerializeField]
    private int damage;

    private bool isActivated = false;

    private AudioSource theAudio;

    [SerializeField]
    private AudioClip sound_Activate;

	// Use this for initialization
	void Start () {
        rigid = GetComponentsInChildren<Rigidbody>();
        theAudio = GetComponent<AudioSource>();
	}
	
    private void OnTriggerEnter(Collider other)
    {
        if (!isActivated)
        {
            if (other.transform.tag != "Untagged") // 플레이어나 동물, 돌멩이 이런거들.
            {
                isActivated = true;
                theAudio.clip = sound_Activate;
                theAudio.Play();

                Destroy(go_Meat); // 고기 제거

                for (int i = 0; i < rigid.Length; i++)
                {
                    rigid[i].useGravity = true;
                    rigid[i].isKinematic = false;
                }

                if(other.transform.name == "Player")
                {
                    other.transform.GetComponent<StatusController>().DecreaseHP(damage);
                    //PlayerController.isActivated = false;
                }

            }
        }
    }
}
